/** Ordered native desktop configuration fields rendered by the shared editor. */
export const configFields = [
  {
    'key': 'Language',
    'options': [
      'zh-CN',
      'en-US',
    ],
  },
  {
    'key': 'WindowChrome',
    'options': [
      'system',
      'traffic',
    ],
  },
  {
    'key': 'ResolutionWidth',
  },
  {
    'key': 'ResolutionHeight',
  },
  {
    'key': 'LaunchMode',
    'options': [
      'window',
      'bordered',
      'borderless',
      'exclusive',
    ],
  },
  {
    'key': 'Url',
  },
  {
    'key': 'Port',
  },
  {
    'key': 'NodePath',
  },
  {
    'key': 'RepoPath',
  },
  {
    'key': 'ToolbarAutoHide',
  },
  {
    'key': 'ToolbarEdgeReveal',
  },
  {
    'key': 'ToolbarHotkey',
  },
  {
    'key': 'FullscreenHotkey',
  },
  {
    'key': 'LoadingStyle',
    'options': [
      'whales',
      'progress',
      'off',
    ],
  },
  {
    'key': 'CloseAction',
    'options': [
      'tray',
      'exit',
    ],
  },
  {
    'key': 'ShowTrayButton',
  },
  {
    'key': 'FullscreenShowToolbar',
  },
  {
    'key': 'FullscreenShowTaskbar',
  },
  {
    'key': 'EnableExtensions',
  },
  {
    'key': 'Extensions',
  },
  {
    'key': 'InjectCss',
  },
  {
    'key': 'InjectJs',
  },
  {
    'key': 'DevTools',
  },
  {
    'key': 'ExternalLinksInBrowser',
  },
  {
    'key': 'Theme',
    'options': [
      'system',
      'light',
      'dark',
    ],
  },
  {
    'key': 'StartPage',
    'options': [
      'home',
      'github',
      'library',
      'installed',
    ],
  },
  {
    'key': 'DiscoverySource',
    'options': [
      'dshmk',
      'community',
      'github',
    ],
  },
  {
    'key': 'PageSize',
    'options': [
      '12',
      '24',
      '48',
      '96',
      '200',
    ],
  },
  {
    'key': 'DetailEntry',
    'options': [
      'button',
      'card',
    ],
  },
  {
    'key': 'DetailMode',
    'options': [
      'side',
      'modal',
      'full',
    ],
  },
  {
    'key': 'DetailContent',
    'options': [
      'native',
      'original',
    ],
  },
  {
    'key': 'AllowDesktopPlugins',
  },
  {
    'key': 'PreloadOnDesktopStart',
  },
] as const

/** Chinese labels and actions for the native configuration editor. */
export const zhConfig = {
  'configTitle': '桌面配置',
  'configDescription': '配置独立保存到 DSH 或 HUB；保存后重启对应应用生效。',
  'configSave': '保存并重启',
  'configSaving': '正在保存…',
  'configRestarting': '配置已保存，正在请求重启…',
  'configSaved': '配置已保存',
  'configTarget': '配置对象',
  'configPending': '有未保存的修改',
  'configClean': '没有未保存的修改',
  'configLeaveTitle': '离开前如何处理修改？',
  'configStay': '继续编辑',
  'configDiscard': '放弃修改',
  'configSaveOnly': '保存并离开',
  'configFailed': '操作失败，修改仍保留在这里。',
  'configConflict': '配置已在其它窗口修改。请保留需要的内容，重新加载后再编辑。',
  'configReload': '重新加载',
  'configStandalone': '打开独立 CONFIG',
  'configUnavailable': '配置编辑仅在桌面程序内可用。',
  'configClose': '返回',
  'configRetryRestart': '重试重启',
  'configAdvanced': '运行环境与扩展',
  'configDisplay': '显示与交互',
  'configResolution': '分辨率预设',
  'configCustom': '自定义',
  'configSavedLater': '配置已保存；在对应程序下次启动时生效。',
  'configFieldLanguage': '语言',
  'configFieldWindowChrome': '窗口按钮样式',
  'configFieldResolutionWidth': '窗口宽度',
  'configFieldResolutionHeight': '窗口高度',
  'configFieldLaunchMode': '启动形式',
  'configFieldUrl': '服务地址',
  'configFieldPort': '端口',
  'configFieldNodePath': 'Node.js 路径',
  'configFieldRepoPath': '本体目录',
  'configFieldToolbarAutoHide': '自动隐藏工具栏',
  'configFieldToolbarEdgeReveal': '鼠标移至顶部呼出工具栏',
  'configFieldToolbarHotkey': '工具栏快捷键',
  'configFieldFullscreenHotkey': '全屏快捷键',
  'configFieldLoadingStyle': '启动加载动画',
  'configFieldCloseAction': '关闭按钮行为',
  'configFieldShowTrayButton': '显示托盘按钮',
  'configFieldFullscreenShowToolbar': '全屏显示上方工具栏',
  'configFieldFullscreenShowTaskbar': '全屏显示系统任务栏',
  'configFieldEnableExtensions': '启用浏览器扩展',
  'configFieldExtensions': '扩展目录（每行一个）',
  'configFieldInjectCss': '自定义 CSS 文件',
  'configFieldInjectJs': '自定义 JavaScript 文件',
  'configFieldDevTools': '开发者工具',
  'configFieldExternalLinksInBrowser': '在浏览器打开外部链接',
  'configFieldTheme': 'HUB 主题',
  'configFieldStartPage': 'HUB 启动页面',
  'configFieldDiscoverySource': '默认市场来源',
  'configFieldPageSize': '每页数量',
  'configFieldDetailEntry': '详情进入方式',
  'configFieldDetailMode': '详情呈现形式',
  'configFieldDetailContent': '详情内容来源',
  'configFieldAllowDesktopPlugins': '允许本体插件影响 HUB',
  'configFieldPreloadOnDesktopStart': 'DSH 就绪后预加载 HUB（一分钟后休眠页面）',
  'configChoicesystem': '跟随系统 / 默认',
  'configChoicetraffic': '红黄绿（窗口模式）',
  'configChoicezh-CN': '简体中文',
  'configChoiceen-US': 'English',
  'configChoicewindow': '窗口',
  'configChoicebordered': '带边框全屏',
  'configChoiceborderless': '无边框全屏',
  'configChoiceexclusive': '真全屏',
  'configChoicewhales': '双鲸鱼',
  'configChoiceprogress': '进度条',
  'configChoiceoff': '关闭',
  'configChoicetray': '缩到托盘',
  'configChoiceexit': '完全退出',
  'configChoicelight': '浅色',
  'configChoicedark': '深色',
  'configChoicehome': '主页',
  'configChoicegithub': 'GitHub 发现',
  'configChoicelibrary': '我的 Setup 库',
  'configChoiceinstalled': '已安装',
  'configChoicedshmk': 'DSHMK',
  'configChoicecommunity': '精选市场',
  'configChoicebutton': '详情按钮',
  'configChoicecard': '整个卡片',
  'configChoiceside': '侧边面板',
  'configChoicemodal': '浮层',
  'configChoicefull': '全页',
  'configChoicenative': 'HUB 重建页面',
  'configChoiceoriginal': '原网页',
} as const

/** English labels and actions for the native configuration editor. */
export const enConfig = {
  'configTitle': 'Desktop configuration',
  'configDescription': 'Settings are stored separately for DSH and HUB. Restart the selected application to apply.',
  'configSave': 'Save and restart',
  'configSaving': 'Saving…',
  'configRestarting': 'Saved. Requesting restart…',
  'configSaved': 'Configuration saved',
  'configTarget': 'Configure',
  'configPending': 'Unsaved changes',
  'configClean': 'No unsaved changes',
  'configLeaveTitle': 'What should happen to your changes?',
  'configStay': 'Keep editing',
  'configDiscard': 'Discard changes',
  'configSaveOnly': 'Save and leave',
  'configFailed': 'The operation failed. Your changes are still here.',
  'configConflict': 'Configuration changed in another window. Retain your edits, then reload before editing again.',
  'configReload': 'Reload',
  'configStandalone': 'Open standalone CONFIG',
  'configUnavailable': 'Configuration editing requires the desktop application.',
  'configClose': 'Back',
  'configRetryRestart': 'Retry restart',
  'configAdvanced': 'Runtime and extensions',
  'configDisplay': 'Display and behavior',
  'configResolution': 'Resolution preset',
  'configCustom': 'Custom',
  'configSavedLater': 'Saved; takes effect when the selected application next starts.',
  'configFieldLanguage': 'Language',
  'configFieldWindowChrome': 'Window controls',
  'configFieldResolutionWidth': 'Window width',
  'configFieldResolutionHeight': 'Window height',
  'configFieldLaunchMode': 'Launch mode',
  'configFieldUrl': 'Service URL',
  'configFieldPort': 'Port',
  'configFieldNodePath': 'Node.js path',
  'configFieldRepoPath': 'Runtime directory',
  'configFieldToolbarAutoHide': 'Auto-hide toolbar',
  'configFieldToolbarEdgeReveal': 'Reveal toolbar at top edge',
  'configFieldToolbarHotkey': 'Toolbar hotkey',
  'configFieldFullscreenHotkey': 'Fullscreen hotkey',
  'configFieldLoadingStyle': 'Startup animation',
  'configFieldCloseAction': 'Close button action',
  'configFieldShowTrayButton': 'Show tray button',
  'configFieldFullscreenShowToolbar': 'Keep toolbar in fullscreen',
  'configFieldFullscreenShowTaskbar': 'Keep taskbar in fullscreen',
  'configFieldEnableExtensions': 'Enable browser extensions',
  'configFieldExtensions': 'Extension directories (one per line)',
  'configFieldInjectCss': 'Custom CSS file',
  'configFieldInjectJs': 'Custom JavaScript file',
  'configFieldDevTools': 'Developer tools',
  'configFieldExternalLinksInBrowser': 'Open external links in browser',
  'configFieldTheme': 'HUB theme',
  'configFieldStartPage': 'HUB start page',
  'configFieldDiscoverySource': 'Default market source',
  'configFieldPageSize': 'Page size',
  'configFieldDetailEntry': 'Detail activation',
  'configFieldDetailMode': 'Detail layout',
  'configFieldDetailContent': 'Detail content',
  'configFieldAllowDesktopPlugins': 'Allow Desktop plugins in HUB',
  'configFieldPreloadOnDesktopStart': 'Preload HUB after DSH is ready (sleep page after one minute)',
  'configChoicesystem': 'System / default',
  'configChoicetraffic': 'Traffic lights (window mode)',
  'configChoicezh-CN': 'Simplified Chinese',
  'configChoiceen-US': 'English',
  'configChoicewindow': 'Window',
  'configChoicebordered': 'Bordered fullscreen',
  'configChoiceborderless': 'Borderless fullscreen',
  'configChoiceexclusive': 'Exclusive fullscreen',
  'configChoicewhales': 'Whales',
  'configChoiceprogress': 'Progress',
  'configChoiceoff': 'Off',
  'configChoicetray': 'Minimize to tray',
  'configChoiceexit': 'Exit',
  'configChoicelight': 'Light',
  'configChoicedark': 'Dark',
  'configChoicehome': 'Home',
  'configChoicegithub': 'GitHub discovery',
  'configChoicelibrary': 'Setup library',
  'configChoiceinstalled': 'Installed',
  'configChoicedshmk': 'DSHMK',
  'configChoicecommunity': 'Curated market',
  'configChoicebutton': 'Details button',
  'configChoicecard': 'Whole card',
  'configChoiceside': 'Side panel',
  'configChoicemodal': 'Modal',
  'configChoicefull': 'Full page',
  'configChoicenative': 'HUB detail page',
  'configChoiceoriginal': 'Original website',
} as const
